name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

        # - name: Sign APK
        #   uses: r0adkll/sign-android-release@v1
        #   with:
        #     releaseDirectory: app/build/outputs/apk/bundle/release
        #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        #     alias: ${{ secrets.KEY_ALIAS }}
        #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        #     keyPassword: ${{ secrets.KEY_PASSWORD }}

        # - name: Upload to Google Play
        #   uses: r0adkll/upload-google-play@v1
        #   with:
        #     serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        #     packageName: com.knowar_client
        #     releaseFile: app/build/outputs/bundle/release/app-release.aab
        #     track: production
