name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run ESLint
        working-directory: ./client
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier Check
        working-directory: ./client
        run: npx prettier --check .

      - name: Run Jest Tests
        working-directory: ./client
        run: npm test
