name: Deploy Node.js app to AWS EC2

on:
  pull_request:
    branches:
      - main
    paths:
      - "server/**"
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or another version if needed

      - name: Install dependencies
        run: npm install
        working-directory: server

      # Here you can run tests or build steps if necessary
      - name: Build
        run: npm run build # make sure this script is defined in your package.json
        working-directory: server

      # Assuming you have set up a method to deploy, such as using SSH to transfer files to EC2
      - name: Deploy to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client
          # Start SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key stored in GitHub Secrets to the agent store
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          # Disable SSH host key checking. Be aware that this is less secure
          export SSH_ARGS="-o StrictHostKeyChecking=no"
          # Sync files to the EC2 instance
          rsync -avz --delete $SSH_ARGS -e "ssh -p $PORT" ./server/ $USERNAME@$HOST:/path/to/your/app
          # Restart server (if required)
          ssh $SSH_ARGS -p $PORT $USERNAME@$HOST "pm2 restart your-app-name"
